jobs:
  Build-Agent:
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'
    name: Build Java Agent
    needs:
    - Cache-Dependencies
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.2.5
    - continue-on-error: true
      name: Restore dependencies from cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Build DongTai-Java-Agent With Maven
      run: 'mvn -version

        mvn -B package -Dmaven.test.skip=true

        '
    - continue-on-error: true
      uses: shogo82148/actions-setup-mysql@v1
      with:
        auto-start: true
        mysql-version: '8.0'
        password: test
        root-password: yuhjnbGYUI
        user: test
  Cache-Dependencies:
    if: github.repository == 'HXSecurity/DongTai-agent-java'
    name: Cache dependencies
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.2.5
    - continue-on-error: true
      id: mvn-cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      if: steps.mvn-cache.outputs.cache-hit != 'true'
      name: Mvn Install
      run: mvn -B compile -Dmaven.test.skip=true
  Upload-To-OSS:
    if: github.event_name == 'push'
    name: Upload To TEST OSS
    needs:
    - Cache-Dependencies
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.2.5
    - continue-on-error: true
      id: version
      name: Get the release version
      run: echo ::set-output name=GITHUB_REF::${GITHUB_REF##*/}
    - continue-on-error: true
      name: Restore dependencies from cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Build DongTai-Java-Agent With Maven
      run: 'mvn -version

        mvn -B package -Dmaven.test.skip=true

        '
    - continue-on-error: true
      name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: dongtai-agent
        path: 'dongtai-agent/target/dongtai-agent.jar

          dongtai-agent/src/main/resources/bin/*

          '
    - continue-on-error: true
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
        endpoint: ${{ secrets.CHART_OSS_ENDPOINT }}
    - continue-on-error: true
      if: ${{ steps.version.outputs.GITHUB_REF }} == develop
      name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -rs dongtai-agent/target/dongtai-agent.jar /agent_test/java/latest/dongtai-agent.jar
          && upload -rs dongtai-agent/src/main/resources/bin/ /agent_test/java/latest/
        bucket: dongtai-helm-charts-1251882848
        region: ap-hongkong
        secret_id: ${{ secrets.TENSECRET_ID }}
        secret_key: ${{ secrets.TENSECRET_KEY }}
    - continue-on-error: true
      if: ${{ steps.version.outputs.GITHUB_REF }} == beta || ${{ steps.version.outputs.GITHUB_REF
        }} == main
      name: Upload COS beta
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -rs dongtai-agent/target/dongtai-agent.jar /agent_${{ steps.version.outputs.GITHUB_REF
          }}/java/latest/dongtai-agent.jar && upload -rs dongtai-agent/src/main/resources/bin/
          /agent_${{ steps.version.outputs.GITHUB_REF }}/java/latest/
        bucket: dongtai-helm-charts-1251882848
        region: ap-hongkong
        secret_id: ${{ secrets.TENSECRET_ID }}
        secret_key: ${{ secrets.TENSECRET_KEY }}
    - continue-on-error: true
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        MAX: false
        PROJECT: agent
        TOKEN_SCA: ${{ secrets.TOKEN_SCA }}
      name: deploy to cluster A
      uses: tscuite/kubectl-helm-action@main
    - continue-on-error: true
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        MAX: true
        PROJECT: agent
        TOKEN_SCA: ${{ secrets.MAX_TOKEN_SCA }}
      name: deploy to cluster B
      uses: tscuite/kubectl-helm-action@main
name: Build Agent and Upload To OSS
on:
  repository_dispatch:
    types: trigger-ga___code-check.yml
