concurrency:
  cancel-in-progress: true
  group: dlc-${{ github.event.pull_request.number || github.ref }}
jobs:
  CheckDeadLinks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      run: sudo npm install -g markdown-link-check
    - continue-on-error: true
      run: "for file in $(find . -name \"*.md\"); do\n  markdown-link-check -c .github/workflows/config/.dlc.json\
        \ -q \"$file\"\ndone\n"
    timeout-minutes: 30
name: Dead Link Checker
on:
  repository_dispatch:
    types: trigger-ga___dead-link-checker.yaml
